export const db = [{
    title:"Title1",
    slug:"title1",
    subtopics:[
        {
            name:"SubTopic1", 
            slug:"subtopic1",
            content:"aaa"
        },
        {
            name:"SubTopic2",
            slug:"subtopic2", 
            content:"bbb"
        },
        {
            name:"SubTopic3", 
            slug:"subtopic3",
            content:"ccc"
        }
    ]
},
{
    title:"Title2",
    slug:"title2",
    subtopics:[
        {
            name:"SubTopic1", 
            slug:"subtopic1",
            content:"aaa"
        },
        {
            name:"SubTopic2",
            slug:"subtopic2", 
            content:"bbb"
        },
        {
            name:"SubTopic3", 
            slug:"subtopic3",
            content:"ccc"
        }
    ]
},
{
    title:"Title3",
    slug:"title3",
    subtopics:[
        {
            name:"SubTopic1", 
            slug:"subtopic1",
            content:"aaa"
        },
        {
            name:"SubTopic2",
            slug:"subtopic2", 
            content:"bbb"
        },
        {
            name:"SubTopic3", 
            slug:"subtopic3",
            content:"ccc"
        }
    ]
},
{
    title:"Title4",
    slug:"title4",
    subtopics:[
        {
            name:"SubTopic1", 
            slug:"subtopic1",
            content:"aaa"
        },
        {
            name:"SubTopic2",
            slug:"subtopic2", 
            content:"bbb"
        },
        {
            name:"SubTopic3", 
            slug:"subtopic3",
            content:"ccc"
        }
    ]
}];